export const CHOOSE_ITEM_ACTION = 'CHOOSE_ITEM_ACTION';
export const CREATE_ITEM_ACTION = 'CREATE_ITEM_ACTION';
export const EDIT_ITEM_ACTION = 'EDIT_ITEM_ACTION';
export const SELECT_ITEM_ACTION = 'SELECT_ITEM_ACTION';
export const UNSELECT_ITEMS_ACTION = 'UNSELECT_ITEMS_ACTION';
export const COPY_ITEMS_ACTION = 'COPY_ITEMS_ACTION';
export const CUT_ITEMS_ACTION = 'CUT_ITEMS_ACTION';
export const PAST_ITEMS_ACTION = 'PAST_ITEMS_ACTION';

const actionTypes = {
  CHOOSE_ITEM_ACTION,
  CREATE_ITEM_ACTION,
  EDIT_ITEM_ACTION,
  SELECT_ITEM_ACTION,
  UNSELECT_ITEMS_ACTION,
  COPY_ITEMS_ACTION,
  CUT_ITEMS_ACTION,
  PAST_ITEMS_ACTION,
}

export default actionTypes;
